baseURL = 'https://intangiblematter.github.io'
languageCode = 'en-us'
title = 'IntangibleMatter'
theme = 'intangibletheme23'
enableGitInfo = true
enableRobotsTXT = true
[menu]
    [[menu.main]]
        name = "Home"
        pre = "home"
        url = "/"
        weight = 1
    [[menu.main]]
        name = "Portfolio"
        pre = "portfolio"
        url = "/portfolio/"
        weight = 2
    [[menu.main]]
        name = "Blog"
        pre = "posts"
        url = "/posts/"
        weight = 3
    #[[menu.main]]
        #name = "Personal"
        #pre = "personal"
        #url = "/personal/"
        #weight = 4
[language]
	languageCode = 'en-ca'


[permalinks]
    posts = '/posts/:year/:month/:day/:title/'



[markup]
	[markup.goldmark]
		[markup.goldmark.renderer]
			unsafe = true
    [markup.highlight]
        anchorLineNos = false
        codeFences = true
        guessSyntax = false
        hl_Lines = ''
        hl_inline = false
        lineAnchors = ''
        lineNoStart = 1
        lineNos = false
        lineNumbersInTable = true
        noClasses = true
        noHl = false
        style = 'fruity'
        tabWidth = 4
